[package]
name = "enumflags_derive"
version = "0.2.2"
authors = ["maik klein <maikklein@googlemail.com>"]
description = "Bitflags"
license = "MIT"
repository = "https://github.com/MaikKlein/enumflags"
keywords = ["enum", "bitflag", "flag", "bitflags"]

[dependencies]
syn = "0.11.4"
quote = "0.3.12"

[lib]
proc-macro = true
